-- Tipos permitidos
create type public.tipo_pedido as enum (
  'delivery',
  'retirada',
  'local'
);

create type public.status_pedido as enum (
  'carrinho',
  'recebido',
  'confirmado',
  'preparando',
  'pronto',
  'a_caminho',
  'entregue',
  'cancelado'
);

create type public.status_entrega as enum (
  'aguardando_atribuicao',
  'atribuida',
  'coletado',
  'a_caminho',
  'entregue',
  'falha'
);

-- Perfil do cliente: ligado ao usuário criado no Supabase Auth
create table public.clientes (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text not null,
  email text not null unique,
  telefone text,
  criado_em timestamptz not null default now()
);

create table public.localidades (
  id bigint generated by default as identity primary key,
  nome text not null,
  endereco text not null,
  cidade text not null,
  uf char(2) not null,
  ativa boolean not null default true
);

create table public.restaurantes (
  id bigint generated by default as identity primary key,
  nome text not null,
  descricao text,
  ativo boolean not null default true
);

-- Restaurante disponível em determinada filial/unidade
create table public.restaurante_localidades (
  id bigint generated by default as identity primary key,
  restaurante_id bigint not null references public.restaurantes(id),
  localidade_id bigint not null references public.localidades(id),
  ativo boolean not null default true,

  unique (restaurante_id, localidade_id)
);

-- Cardápio e preços variam conforme a unidade
create table public.itens_cardapio (
  id bigint generated by default as identity primary key,
  restaurante_localidade_id bigint not null
    references public.restaurante_localidades(id) on delete cascade,

  nome text not null,
  descricao text,
  categoria text,
  preco numeric(10,2) not null check (preco >= 0),
  disponivel boolean not null default true,

  unique (restaurante_localidade_id, id)
);

create table public.mesas (
  id bigint generated by default as identity primary key,
  restaurante_localidade_id bigint not null
    references public.restaurante_localidades(id) on delete cascade,

  numero text not null,
  ativa boolean not null default true,

  unique (restaurante_localidade_id, numero),
  unique (restaurante_localidade_id, id)
);

create table public.entregadores (
  id bigint generated by default as identity primary key,
  nome text not null,
  telefone text not null,
  ativo boolean not null default true
);

-- Carrinho e pedido usam a mesma tabela.
-- Enquanto estiver em "carrinho", ainda não foi fechado.
create table public.pedidos (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references public.clientes(id),
  restaurante_localidade_id bigint not null
    references public.restaurante_localidades(id),

  tipo public.tipo_pedido not null,
  mesa_id bigint,
  endereco_entrega text,
  taxa_entrega numeric(10,2) not null default 0,

  status_atual public.status_pedido not null default 'carrinho',

  subtotal numeric(10,2) not null default 0,
  total numeric(10,2)
    generated always as (subtotal + taxa_entrega) stored,

  criado_em timestamptz not null default now(),
  fechado_em timestamptz,

  -- Garante que item do pedido pertença à mesma unidade
  unique (id, restaurante_localidade_id),

  -- Garante que a mesa é daquela unidade/restaurante
  foreign key (restaurante_localidade_id, mesa_id)
    references public.mesas(restaurante_localidade_id, id),

  -- Mesa só pode existir no consumo local.
  -- Taxa e endereço só podem existir para delivery.
  check (
    (mesa_id is null or tipo = 'local')
    and (tipo = 'delivery' or taxa_entrega = 0)
    and (tipo = 'delivery' or endereco_entrega is null)
    and (tipo = 'delivery' or status_atual <> 'a_caminho')
  )
);

create table public.pedido_itens (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null,
  restaurante_localidade_id bigint not null,
  item_cardapio_id bigint not null,

  quantidade integer not null check (quantidade > 0),
  preco_unitario numeric(10,2) not null check (preco_unitario >= 0),
  observacao text,

  -- Item deve pertencer ao mesmo pedido e à mesma unidade
  foreign key (pedido_id, restaurante_localidade_id)
    references public.pedidos(id, restaurante_localidade_id)
    on delete cascade,

  foreign key (restaurante_localidade_id, item_cardapio_id)
    references public.itens_cardapio(restaurante_localidade_id, id)
);

-- Só será criada para pedidos do tipo delivery
create table public.entregas (
  pedido_id bigint primary key
    references public.pedidos(id) on delete cascade,

  entregador_id bigint references public.entregadores(id),
  status public.status_entrega not null default 'aguardando_atribuicao',

  atribuido_em timestamptz,
  saiu_para_entrega_em timestamptz,
  entregue_em timestamptz
);

create table public.pedido_status_historico (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null
    references public.pedidos(id) on delete cascade,

  status public.status_pedido not null,
  observacao text,
  criado_em timestamptz not null default now()
);

-- Atualiza o subtotal quando itens são incluídos/removidos do carrinho
create or replace function public.recalcular_subtotal_pedido(p_pedido_id bigint)
returns void
language plpgsql
as $$
begin
  update public.pedidos
     set subtotal = coalesce((
       select sum(quantidade * preco_unitario)
       from public.pedido_itens
       where pedido_id = p_pedido_id
     ), 0)
   where id = p_pedido_id;
end;
$$;

create or replace function public.trg_recalcular_subtotal()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'DELETE' then
    perform public.recalcular_subtotal_pedido(old.pedido_id);
    return old;
  end if;

  perform public.recalcular_subtotal_pedido(new.pedido_id);

  if tg_op = 'UPDATE' and old.pedido_id is distinct from new.pedido_id then
    perform public.recalcular_subtotal_pedido(old.pedido_id);
  end if;

  return new;
end;
$$;

create trigger pedido_itens_recalcula_subtotal
after insert or update or delete on public.pedido_itens
for each row execute function public.trg_recalcular_subtotal();

-- Impede atribuir entregador a retirada ou consumo no local
create or replace function public.trg_validar_entrega_delivery()
returns trigger
language plpgsql
as $$
begin
  if not exists (
    select 1
    from public.pedidos
    where id = new.pedido_id
      and tipo = 'delivery'
  ) then
    raise exception 'Entregador só pode ser vinculado a pedidos Delivery.';
  end if;

  return new;
end;
$$;

create trigger entregas_apenas_delivery
before insert or update on public.entregas
for each row execute function public.trg_validar_entrega_delivery();

-- Fecha o carrinho e transforma-o em pedido
create or replace function public.fechar_pedido(p_pedido_id bigint)
returns void
language plpgsql
as $$
declare
  v_tipo public.tipo_pedido;
  v_status public.status_pedido;
  v_endereco text;
begin
  select tipo, status_atual, endereco_entrega
    into v_tipo, v_status, v_endereco
  from public.pedidos
  where id = p_pedido_id
  for update;

  if not found then
    raise exception 'Pedido não encontrado.';
  end if;

  if v_status <> 'carrinho' then
    raise exception 'Este pedido já foi fechado.';
  end if;

  if not exists (
    select 1 from public.pedido_itens where pedido_id = p_pedido_id
  ) then
    raise exception 'O pedido precisa ter ao menos um item.';
  end if;

  if v_tipo = 'delivery' and nullif(trim(v_endereco), '') is null then
    raise exception 'Pedidos Delivery precisam de endereço.';
  end if;

  update public.pedidos
     set status_atual = 'recebido',
         fechado_em = now()
   where id = p_pedido_id;

  insert into public.pedido_status_historico (pedido_id, status, observacao)
  values (p_pedido_id, 'recebido', 'Pedido fechado pelo cliente.');
end;
$$;

-- Texto exibido ao cliente muda conforme o tipo de pedido
create or replace view public.vw_acompanhamento_pedidos as
select
  p.id as pedido_id,
  p.cliente_id,
  p.tipo,
  p.status_atual,
  p.total,
  p.criado_em,
  p.fechado_em,

  case
    when p.status_atual = 'carrinho' then 'Carrinho em edição'
    when p.status_atual = 'recebido' then 'Pedido recebido'
    when p.status_atual = 'confirmado' then 'Pedido confirmado'
    when p.status_atual = 'preparando' then 'Sendo preparado'
    when p.status_atual = 'pronto' and p.tipo = 'retirada'
      then 'Pronto para retirar'
    when p.status_atual = 'pronto' and p.tipo = 'local'
      then 'Pronto para servir'
    when p.status_atual = 'pronto' and p.tipo = 'delivery'
      then 'Aguardando entregador'
    when p.status_atual = 'a_caminho'
      then 'A caminho'
    when p.status_atual = 'entregue' and p.tipo = 'retirada'
      then 'Pedido retirado'
    when p.status_atual = 'entregue' and p.tipo = 'local'
      then 'Pedido finalizado no local'
    when p.status_atual = 'entregue'
      then 'Pedido entregue'
    when p.status_atual = 'cancelado'
      then 'Pedido cancelado'
  end as status_exibicao
from public.pedidos p;

-- Índices para buscas mais rápidas
create index idx_pedidos_cliente on public.pedidos(cliente_id);
create index idx_pedidos_localidade on public.pedidos(restaurante_localidade_id);
create index idx_itens_cardapio_localidade
  on public.itens_cardapio(restaurante_localidade_id);
